---
- hosts: all
  sudo: true

  roles:
    - {role: consul, consul_is_server:false, consul_is_ui:false, consul_start_join: ["192.168.50.4"] }

  tasks: 
    - name: install consul
      include: tasks/install.yml
