---
#consul config files

- name: consul config - base 
  template:
    src=base.json.j2
    dest={{ consul_config_dir }}/base.json
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
  notify: restart consul

- name: consul config - network
  template:
    src=network.json.j2
    dest={{ consul_config_dir }}/network.json
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
  notify: restart consul

- name: consul config - auth
  template:
    src=auth.json.j2
    dest={{ consul_config_dir }}/auth.json
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
  notify: restart consul

