---

- name: download consul
  get_url:
    url={{ consul_uri }} 
    dest={{ consul_download_folder }}
  register: consul_was_downloaded

- name: create consul group
  group:
    name={{ consul_group }}
    state=present

- name: create consul user
  user:
    name={{ consul_user }}
    group={{ consul_group }}

- name: create consul directories
  file:
    state=directory
    path={{ item }}
    owner={{ consul_user }}
    group={{ consul_group }}
  with_items:
    - "{{ consul_install_dir }}"
    - "{{ consul_data_dir }}"
    - "{{ consul_config_dir }}"
    - "{{ consul_log_dir }}"

- name: copy and unpack
  unarchive:
    src={{ consul_download_folder }}/{{ consul_archive }}
    dest={{ consul_install_dir }}
    copy=no
  when: consul_was_downloaded|changed


