---

- include: depend.yml

- include: install_binary.yml

- name: add consul to path
  template: 
    src=environment.sh.j2
    dest=/etc/profile.d/consul.sh
    owner=root
    group=root
    mode=0755

- name: setup consul configs
  include: config.yml

- name: consul - service
  include: runit_service.yml
  vars:
    service_name: "{{ consul_service_name }}"
    service_user: "{{ consul_user }}"
    service_command: "{{ consul_install_dir }}/consul agent -config-dir {{ consul_config_dir }}"
    service_env_vars:
      GOMAXPROCS: "{{ansible_processor_cores + 1}}"

