---
- name: runit - create service directories
  file:
    state=directory
    path={{ item }}
    owner=root
    group=root
  with_items:
    - /etc/sv/{{ consul_service_name }}
    - /etc/sv/{{ consul_service_name }}/log
    - /etc/sv/{{ consul_service_name }}/env

- name: runit - main service config
  template:
    src=runit.j2
    dest=/etc/sv/{{ consul_service_name }}/run
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
  notify: restart consul

- name: runit - set env
  template:
    src=GOMAXPROCS.j2
    dest=/etc/sv/{{ consul_service_name }}/env/GOMAXPROCS
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
  notify: restart consul

- name: runit - set log config
  template:
    src=runit_log.j2
    dest=/etc/sv/{{ consul_service_name }}/log/run
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
  notify: restart consul

- name: runit - symlink service
  file: src=/etc/sv/{{ consul_service_name }} dest=/etc/service/{{ consul_service_name }} state=link
  notify: restart consul

- name: runit - Wait for service to start
  wait_for: path=/etc/sv/{{ consul_service_name }}/supervise/ok timeout=7

- name: runit - ensure started  
  runit: name={{ consul_service_name }} state=started timeout=30

