---

- name: service - setup and run
  runit:
    name: "{{ consul_service_name }}"
    enabled: yes
    state: start
    timeout: 10
    user: "{{ consul_user }}"
    command: "{{ consul_install_dir }}/consul agent -config-dir {{ consul_config_dir }}"
    env_vars:
      GOMAXPROCS: "{{ansible_processor_cores + 1}}"
  register: consul_service_status

